eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
   instance:
    hostname: localhost 
    
payment_service:
   endpoints:
      dopayment: http://PAYMENT-SERVICE/payment/doPayment
   payment: 
      gateway: 
         flag: false
